Able to detect gzip-compressed FITS files even if they don't have the .gz extension in filename.
`~sunpy.io.file_tools.detect_filetype` now looks for the right file signature while checking
for gzipped FITS files.
