scanner:
  diff_only: False

pycodestyle:
  max-line-length: 100
  exclude:
    - setup.py
    - docs/conf.py
    - sunpy/__init__.py
    - sunpy/extern/

descending_issues_order: True

message:
  opened:
    header: "Hello @{name}! Thanks for opening this PR. "
    footer: "Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)"
  updated:
    header: "Hello @{name}! Thanks for updating this PR. "
    footer: ""
  no_errors: "There are currently no PEP 8 issues detected in this Pull Request. Cheers!"
