pycodestyle:
  max-line-length: 100
  exclude:
    - setup.py
    - ez_setup.py
    - ah_bootstrap.py
    - astropy_helpers/
    - docs/conf.py
    - sunpy/cm/color_tables.py
  descending_issues_order: True
