version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yml docs/conf.py
    post_install:
      - pip install -U git+https://github.com/ayshih/sphinx@fix_inheritance_diagrams

conda:
  environment: .rtd-environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
   install:
     - method: pip
       extra_requirements:
        - all
        - docs
       path: .
