version: 2

python:
   version: 3.7
   install:
      # Use this to override dep versions.
      - requirements: docs/rtd_requirements.txt
      - method: pip
        path: .
        extra_requirements:
           - dev
