jobs:
- job: ${{ format(parameters.name) }}
  pool:
    ${{ if eq(parameters.os, 'windows') }}:
      vmImage: vs2017-win2016
    ${{ if eq(parameters.os, 'macos') }}:
      vmImage: macOS 10.13
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: Ubuntu 16.04

  steps:

  - ${{ if eq(parameters.os, 'linux') }}:
    - script: |
        sudo apt-get install -y libopenjpeg5
      displayName: apt install openjpeg

  - ${{ if eq(parameters.os, 'macos') }}:
    - script: |
        brew install openjpeg
      displayName: brew install openjpeg

  - ${{ if contains(parameters.tox, 'conda') }}:
    - task: CondaEnvironment@1
      displayName: 'Create conda environment'
      inputs:
        createCustomEnvironment: True
        environmentName: "test"
        createOptions: python="3.6"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: pip install --upgrade tox
    displayName: install tox

  - ${{ if contains(parameters.tox, 'conda') }}:
    - script: pip install --upgrade tox-conda
      displayName: install tox-conda

  - script: tox -e ${{ parameters.tox }} --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
    displayName: run tox

  - script: |
      pip install --upgrade codecov
      codecov --name ${{ format(parameters.name) }}
    displayName: run codecov
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for ${{ format(parameters.name) }}'

  - ${{ if contains(parameters.tox, 'online') }}:
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
