name: sunpy
channels:
  - sunpy
  - defaults
dependencies:
  - graphviz!=2.42.*
  - openjpeg
  - pip
  - python
  - sphinx
  - pip:
    - asdf
    - astropy
    - astroquery
    - beautifulsoup4
    - drms
    - extension_helpers
    - glymur
    - hypothesis
    - jplephem
    - matplotlib
    - numpy
    - pandas
    - parfive
    - pytest
    - python-dateutil
    - reproject
    - ruamel.yaml
    - scikit-image
    - scipy
    - sphinx-astropy
    - sphinx-gallery
    - sqlalchemy
    - sunpy-sphinx-theme
    - towncrier
    - tqdm
    - zeep
