# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/matt/programming/sunpy/sunpy/gui/ui/mainwindow/mainwindow.ui'
#
# Created: Sat Aug 27 23:54:41 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(662, 615)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPlot = QtGui.QMenu(self.menubar)
        self.menuPlot.setObjectName(_fromUtf8("menuPlot"))
        self.menuView = QtGui.QMenu(self.menuPlot)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.fileToolBar = QtGui.QToolBar(MainWindow)
        self.fileToolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fileToolBar.setObjectName(_fromUtf8("fileToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.fileToolBar)
        MainWindow.insertToolBarBreak(self.fileToolBar)
        self.plotToolBar = QtGui.QToolBar(MainWindow)
        self.plotToolBar.setWindowOpacity(1.0)
        self.plotToolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plotToolBar.setObjectName(_fromUtf8("plotToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.plotToolBar)
        self.actionOpen_file = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/open_plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_file.setIcon(icon)
        self.actionOpen_file.setObjectName(_fromUtf8("actionOpen_file"))
        self.actionReset_view = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset_view.setIcon(icon1)
        self.actionReset_view.setObjectName(_fromUtf8("actionReset_view"))
        self.actionPrevious_view = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious_view.setIcon(icon2)
        self.actionPrevious_view.setObjectName(_fromUtf8("actionPrevious_view"))
        self.actionNext_view = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext_view.setIcon(icon3)
        self.actionNext_view.setObjectName(_fromUtf8("actionNext_view"))
        self.actionPan = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/move.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon4)
        self.actionPan.setObjectName(_fromUtf8("actionPan"))
        self.actionConfigure_subplots = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/subplots.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigure_subplots.setIcon(icon5)
        self.actionConfigure_subplots.setObjectName(_fromUtf8("actionConfigure_subplots"))
        self.actionZoom = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/zoom_to_rect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon6)
        self.actionZoom.setObjectName(_fromUtf8("actionZoom"))
        self.actionChange_color_map = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/change_cm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChange_color_map.setIcon(icon7)
        self.actionChange_color_map.setObjectName(_fromUtf8("actionChange_color_map"))
        self.actionSave_plot = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/save_plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_plot.setIcon(icon8)
        self.actionSave_plot.setObjectName(_fromUtf8("actionSave_plot"))
        self.actionExit_PlotMan = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit_PlotMan.setIcon(icon9)
        self.actionExit_PlotMan.setObjectName(_fromUtf8("actionExit_PlotMan"))
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionExit_PlotMan)
        self.menuView.addAction(self.actionNext_view)
        self.menuView.addAction(self.actionPrevious_view)
        self.menuView.addAction(self.actionReset_view)
        self.menuPlot.addAction(self.menuView.menuAction())
        self.menuPlot.addAction(self.actionPan)
        self.menuPlot.addAction(self.actionZoom)
        self.menuPlot.addAction(self.actionChange_color_map)
        self.menuPlot.addAction(self.actionConfigure_subplots)
        self.menuPlot.addAction(self.actionSave_plot)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.fileToolBar.addAction(self.actionOpen_file)
        self.fileToolBar.addAction(self.actionExit_PlotMan)
        self.plotToolBar.addAction(self.actionReset_view)
        self.plotToolBar.addAction(self.actionPrevious_view)
        self.plotToolBar.addAction(self.actionNext_view)
        self.plotToolBar.addAction(self.actionPan)
        self.plotToolBar.addAction(self.actionConfigure_subplots)
        self.plotToolBar.addAction(self.actionZoom)
        self.plotToolBar.addAction(self.actionChange_color_map)
        self.plotToolBar.addSeparator()
        self.plotToolBar.addAction(self.actionSave_plot)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit_PlotMan, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlot.setTitle(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.fileToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.plotToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_file.setText(QtGui.QApplication.translate("MainWindow", "Open file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_file.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a FITS file for plotting...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_file.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open a FITS file for plotting...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_file.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_view.setText(QtGui.QApplication.translate("MainWindow", "Reset view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_view.setToolTip(QtGui.QApplication.translate("MainWindow", "Reset original view.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_view.setStatusTip(QtGui.QApplication.translate("MainWindow", "Reset original view.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_view.setText(QtGui.QApplication.translate("MainWindow", "Previous view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_view.setToolTip(QtGui.QApplication.translate("MainWindow", "Go back to the previous view.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_view.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show subplot configurator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_view.setText(QtGui.QApplication.translate("MainWindow", "Next view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_view.setToolTip(QtGui.QApplication.translate("MainWindow", "Go forward to the next view.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_view.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show subplot configurator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPan.setText(QtGui.QApplication.translate("MainWindow", "Pan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPan.setToolTip(QtGui.QApplication.translate("MainWindow", "Pan axes with left mouse, zoom with right.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPan.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show subplot configurator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure_subplots.setText(QtGui.QApplication.translate("MainWindow", "Configure subplots...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure_subplots.setToolTip(QtGui.QApplication.translate("MainWindow", "Show subplot configurator.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure_subplots.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show subplot configurator.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom to rectangle.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setStatusTip(QtGui.QApplication.translate("MainWindow", "Zoom to rectangle.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_color_map.setText(QtGui.QApplication.translate("MainWindow", "Change color map...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_color_map.setToolTip(QtGui.QApplication.translate("MainWindow", "Show color map selector...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_color_map.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show color map selector...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_plot.setText(QtGui.QApplication.translate("MainWindow", "Save plot...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_plot.setToolTip(QtGui.QApplication.translate("MainWindow", "Save plot to PNG...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_plot.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save plot to PNG...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_plot.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_PlotMan.setText(QtGui.QApplication.translate("MainWindow", "Exit PlotMan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_PlotMan.setToolTip(QtGui.QApplication.translate("MainWindow", "Close the application.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_PlotMan.setStatusTip(QtGui.QApplication.translate("MainWindow", "Close the application.", None, QtGui.QApplication.UnicodeUTF8))

from resources import qrc_resources
