"""
=================================================
Drawing heliographic longitude and latitude lines
=================================================

This example demonstrates how you can draw your own Stonyhurst
longitude and latitude lines.
"""
import matplotlib.pyplot as plt
import numpy as np

import astropy.units as u
from astropy.coordinates import SkyCoord

import sunpy.map
from sunpy.coordinates import frames
from sunpy.data.sample import AIA_171_IMAGE

###############################################################################
# We will demonstrate the coordinate transformations that occur under the
# hood to show the heliographic grid lines of longitude latitude.
# We first create a map using the sample data.

aia = sunpy.map.Map(AIA_171_IMAGE)

###############################################################################
# Let's first specify a single heliographic point coordinate.

stonyhurst_center = SkyCoord(12 * u.deg, 12 * u.deg,
                             frame=frames.HeliographicStonyhurst)

###############################################################################
# Next we transform it into the coordinate frame of our map which is helioprojective.

hpc_stonyhurst_center = stonyhurst_center.transform_to(aia.coordinate_frame)
print(hpc_stonyhurst_center)

###############################################################################
# Now let's define two lines, one of constant longitude and one of constant latitude.
# We don't need to explicitly transform them to the coordinate frame of our
# map because they will be transformed automatically when plotted.

num_points = 100
lat_value = 12 * u.deg
lon_value = 35 * u.deg
lon = SkyCoord(np.ones(num_points) * lon_value,
               np.linspace(-90, 90, num_points) * u.deg,
               frame=frames.HeliographicStonyhurst)
lat = SkyCoord(np.linspace(-90, 90, num_points) * u.deg,
               np.ones(num_points) * lat_value, frame=frames.HeliographicStonyhurst)

###############################################################################
# Now let's plot the results. We'll overlay the autogenerated lon/lat
# grid as well for comparison.

fig = plt.figure()
ax = fig.add_subplot(projection=aia)
aia.plot(axes=ax, clip_interval=(1, 99.99)*u.percent)
ax.plot_coord(lon, color="lightblue")
ax.plot_coord(lat, color="tomato")
aia.draw_grid(axes=ax)

plt.show()
