# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/matt/programming/sunpy/sunpy/gui/ui/mainwindow/widgets/coloroptions.ui'
#
# Created: Thu Sep  8 20:09:18 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ColorOptions(object):
    def setupUi(self, ColorOptions):
        ColorOptions.setObjectName(_fromUtf8("ColorOptions"))
        ColorOptions.resize(387, 443)
        self.verticalLayout_4 = QtGui.QVBoxLayout(ColorOptions)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(ColorOptions)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setContentsMargins(3, 6, 3, 3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cmListWidget = QtGui.QListWidget(self.groupBox)
        self.cmListWidget.setObjectName(_fromUtf8("cmListWidget"))
        self.verticalLayout.addWidget(self.cmListWidget)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.line = QtGui.QFrame(ColorOptions)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(ColorOptions)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(ColorOptions)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.clipMinDoubleSpinBox = QtGui.QDoubleSpinBox(ColorOptions)
        self.clipMinDoubleSpinBox.setDecimals(2)
        self.clipMinDoubleSpinBox.setMinimum(0.01)
        self.clipMinDoubleSpinBox.setMaximum(2000.0)
        self.clipMinDoubleSpinBox.setSingleStep(0.01)
        self.clipMinDoubleSpinBox.setObjectName(_fromUtf8("clipMinDoubleSpinBox"))
        self.horizontalLayout.addWidget(self.clipMinDoubleSpinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(ColorOptions)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.clipMaxDoubleSpinBox = QtGui.QDoubleSpinBox(ColorOptions)
        self.clipMaxDoubleSpinBox.setMinimum(0.01)
        self.clipMaxDoubleSpinBox.setMaximum(2000.0)
        self.clipMaxDoubleSpinBox.setObjectName(_fromUtf8("clipMaxDoubleSpinBox"))
        self.horizontalLayout_2.addWidget(self.clipMaxDoubleSpinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(ColorOptions)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.scalingComboBox = QtGui.QComboBox(ColorOptions)
        self.scalingComboBox.setObjectName(_fromUtf8("scalingComboBox"))
        self.scalingComboBox.addItem(_fromUtf8(""))
        self.scalingComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.scalingComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(ColorOptions)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.gammaSlider = QtGui.QSlider(ColorOptions)
        self.gammaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gammaSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.gammaSlider.setObjectName(_fromUtf8("gammaSlider"))
        self.horizontalLayout_7.addWidget(self.gammaSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.line_2 = QtGui.QFrame(ColorOptions)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_4.addWidget(self.line_2)
        self.groupBox_2 = QtGui.QGroupBox(ColorOptions)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setContentsMargins(3, 6, 3, 3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.histogramWidget = QtGui.QWidget(self.groupBox_2)
        self.histogramWidget.setObjectName(_fromUtf8("histogramWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.histogramWidget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_2.addWidget(self.histogramWidget)
        self.verticalLayout_4.addWidget(self.groupBox_2)

        self.retranslateUi(ColorOptions)
        QtCore.QMetaObject.connectSlotsByName(ColorOptions)

    def retranslateUi(self, ColorOptions):
        ColorOptions.setWindowTitle(QtGui.QApplication.translate("ColorOptions", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ColorOptions", "Color Map", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ColorOptions", "Clip values:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ColorOptions", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ColorOptions", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ColorOptions", "Scaling:", None, QtGui.QApplication.UnicodeUTF8))
        self.scalingComboBox.setItemText(0, QtGui.QApplication.translate("ColorOptions", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.scalingComboBox.setItemText(1, QtGui.QApplication.translate("ColorOptions", "Logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ColorOptions", "Gamma:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ColorOptions", "Histogram", None, QtGui.QApplication.UnicodeUTF8))

