# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rgb_composite.ui'
#
# Created: Tue Feb 14 13:31:49 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RGBComposite(object):
    def setupUi(self, RGBComposite):
        RGBComposite.setObjectName(_fromUtf8("RGBComposite"))
        RGBComposite.resize(1080, 972)
        RGBComposite.setWindowTitle(QtGui.QApplication.translate("RGBComposite", "SunPy - RGB Composite Image Demo", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(RGBComposite)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1031, 875))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.outerContainer = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.outerContainer.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.outerContainer.setMargin(0)
        self.outerContainer.setMargin(0)
        self.outerContainer.setObjectName(_fromUtf8("outerContainer"))
        self.compositeContainer = QtGui.QHBoxLayout()
        self.compositeContainer.setContentsMargins(-1, 10, -1, -1)
        self.compositeContainer.setObjectName(_fromUtf8("compositeContainer"))
        self.compositePlaceholder = QtGui.QWidget(self.verticalLayoutWidget)
        self.compositePlaceholder.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compositePlaceholder.sizePolicy().hasHeightForWidth())
        self.compositePlaceholder.setSizePolicy(sizePolicy)
        self.compositePlaceholder.setMinimumSize(QtCore.QSize(512, 512))
        self.compositePlaceholder.setMaximumSize(QtCore.QSize(512, 512))
        self.compositePlaceholder.setObjectName(_fromUtf8("compositePlaceholder"))
        self.compositeContainer.addWidget(self.compositePlaceholder)
        self.outerContainer.addLayout(self.compositeContainer)
        self.dateForm = QtGui.QHBoxLayout()
        self.dateForm.setContentsMargins(10, -1, 10, -1)
        self.dateForm.setObjectName(_fromUtf8("dateForm"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setText(QtGui.QApplication.translate("RGBComposite", "Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.dateForm.addWidget(self.label)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.verticalLayoutWidget)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(220, 0))
        self.dateTimeEdit.setTime(QtCore.QTime(15, 0, 0))
        self.dateTimeEdit.setDisplayFormat(QtGui.QApplication.translate("RGBComposite", "yyyy/MM/dd HH:mm:ss UT", None, QtGui.QApplication.UnicodeUTF8))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.dateForm.addWidget(self.dateTimeEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.dateForm.addItem(spacerItem)
        self.outerContainer.addLayout(self.dateForm)
        self.wavelengthForm = QtGui.QHBoxLayout()
        self.wavelengthForm.setMargin(10)
        self.wavelengthForm.setObjectName(_fromUtf8("wavelengthForm"))
        self.redContainer = QtGui.QVBoxLayout()
        self.redContainer.setObjectName(_fromUtf8("redContainer"))
        self.redLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.redLabel.setText(QtGui.QApplication.translate("RGBComposite", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.redLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.redLabel.setObjectName(_fromUtf8("redLabel"))
        self.redContainer.addWidget(self.redLabel)
        self.redPreview = QtGui.QHBoxLayout()
        self.redPreview.setObjectName(_fromUtf8("redPreview"))
        self.redPlaceholder = QtGui.QWidget(self.verticalLayoutWidget)
        self.redPlaceholder.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redPlaceholder.sizePolicy().hasHeightForWidth())
        self.redPlaceholder.setSizePolicy(sizePolicy)
        self.redPlaceholder.setMinimumSize(QtCore.QSize(128, 128))
        self.redPlaceholder.setMaximumSize(QtCore.QSize(128, 128))
        self.redPlaceholder.setObjectName(_fromUtf8("redPlaceholder"))
        self.redPreview.addWidget(self.redPlaceholder)
        self.redContainer.addLayout(self.redPreview)
        self.redWavelength = QtGui.QHBoxLayout()
        self.redWavelength.setObjectName(_fromUtf8("redWavelength"))
        self.redWavelengthLabel = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redWavelengthLabel.sizePolicy().hasHeightForWidth())
        self.redWavelengthLabel.setSizePolicy(sizePolicy)
        self.redWavelengthLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.redWavelengthLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.redWavelengthLabel.setText(QtGui.QApplication.translate("RGBComposite", "Wavelength: ", None, QtGui.QApplication.UnicodeUTF8))
        self.redWavelengthLabel.setObjectName(_fromUtf8("redWavelengthLabel"))
        self.redWavelength.addWidget(self.redWavelengthLabel)
        self.redWavelengthSelect = QtGui.QComboBox(self.verticalLayoutWidget)
        self.redWavelengthSelect.setMinimumSize(QtCore.QSize(130, 0))
        self.redWavelengthSelect.setObjectName(_fromUtf8("redWavelengthSelect"))
        self.redWavelength.addWidget(self.redWavelengthSelect)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.redWavelength.addItem(spacerItem1)
        self.redContainer.addLayout(self.redWavelength)
        self.redWeight = QtGui.QHBoxLayout()
        self.redWeight.setObjectName(_fromUtf8("redWeight"))
        self.redWeightLabel = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redWeightLabel.sizePolicy().hasHeightForWidth())
        self.redWeightLabel.setSizePolicy(sizePolicy)
        self.redWeightLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.redWeightLabel.setText(QtGui.QApplication.translate("RGBComposite", "Weight: ", None, QtGui.QApplication.UnicodeUTF8))
        self.redWeightLabel.setObjectName(_fromUtf8("redWeightLabel"))
        self.redWeight.addWidget(self.redWeightLabel)
        self.redWeightSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.redWeightSlider.setMaximum(100)
        self.redWeightSlider.setSingleStep(5)
        self.redWeightSlider.setProperty("value", 100)
        self.redWeightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redWeightSlider.setObjectName(_fromUtf8("redWeightSlider"))
        self.redWeight.addWidget(self.redWeightSlider)
        self.redContainer.addLayout(self.redWeight)
        self.wavelengthForm.addLayout(self.redContainer)
        self.greenContainer = QtGui.QVBoxLayout()
        self.greenContainer.setObjectName(_fromUtf8("greenContainer"))
        self.greenLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.greenLabel.setText(QtGui.QApplication.translate("RGBComposite", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.greenLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.greenLabel.setObjectName(_fromUtf8("greenLabel"))
        self.greenContainer.addWidget(self.greenLabel)
        self.greenPreview = QtGui.QHBoxLayout()
        self.greenPreview.setObjectName(_fromUtf8("greenPreview"))
        self.greenPlaceholder = QtGui.QWidget(self.verticalLayoutWidget)
        self.greenPlaceholder.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenPlaceholder.sizePolicy().hasHeightForWidth())
        self.greenPlaceholder.setSizePolicy(sizePolicy)
        self.greenPlaceholder.setMinimumSize(QtCore.QSize(128, 128))
        self.greenPlaceholder.setMaximumSize(QtCore.QSize(128, 128))
        self.greenPlaceholder.setObjectName(_fromUtf8("greenPlaceholder"))
        self.greenPreview.addWidget(self.greenPlaceholder)
        self.greenContainer.addLayout(self.greenPreview)
        self.greenWavelength = QtGui.QHBoxLayout()
        self.greenWavelength.setObjectName(_fromUtf8("greenWavelength"))
        self.greenWavelengthLabel = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenWavelengthLabel.sizePolicy().hasHeightForWidth())
        self.greenWavelengthLabel.setSizePolicy(sizePolicy)
        self.greenWavelengthLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.greenWavelengthLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.greenWavelengthLabel.setText(QtGui.QApplication.translate("RGBComposite", "Wavelength: ", None, QtGui.QApplication.UnicodeUTF8))
        self.greenWavelengthLabel.setObjectName(_fromUtf8("greenWavelengthLabel"))
        self.greenWavelength.addWidget(self.greenWavelengthLabel)
        self.greenWavelengthSelect = QtGui.QComboBox(self.verticalLayoutWidget)
        self.greenWavelengthSelect.setMinimumSize(QtCore.QSize(130, 0))
        self.greenWavelengthSelect.setObjectName(_fromUtf8("greenWavelengthSelect"))
        self.greenWavelength.addWidget(self.greenWavelengthSelect)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.greenWavelength.addItem(spacerItem2)
        self.greenContainer.addLayout(self.greenWavelength)
        self.greenWeight = QtGui.QHBoxLayout()
        self.greenWeight.setObjectName(_fromUtf8("greenWeight"))
        self.greenWeightLabel = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenWeightLabel.sizePolicy().hasHeightForWidth())
        self.greenWeightLabel.setSizePolicy(sizePolicy)
        self.greenWeightLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.greenWeightLabel.setText(QtGui.QApplication.translate("RGBComposite", "Weight: ", None, QtGui.QApplication.UnicodeUTF8))
        self.greenWeightLabel.setObjectName(_fromUtf8("greenWeightLabel"))
        self.greenWeight.addWidget(self.greenWeightLabel)
        self.greenWeightSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.greenWeightSlider.setMaximum(100)
        self.greenWeightSlider.setProperty("value", 100)
        self.greenWeightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenWeightSlider.setObjectName(_fromUtf8("greenWeightSlider"))
        self.greenWeight.addWidget(self.greenWeightSlider)
        self.greenContainer.addLayout(self.greenWeight)
        self.wavelengthForm.addLayout(self.greenContainer)
        self.blueContainer = QtGui.QVBoxLayout()
        self.blueContainer.setObjectName(_fromUtf8("blueContainer"))
        self.blueLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.blueLabel.setText(QtGui.QApplication.translate("RGBComposite", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.blueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.blueLabel.setObjectName(_fromUtf8("blueLabel"))
        self.blueContainer.addWidget(self.blueLabel)
        self.bluePreview = QtGui.QHBoxLayout()
        self.bluePreview.setObjectName(_fromUtf8("bluePreview"))
        self.bluePlaceholder = QtGui.QWidget(self.verticalLayoutWidget)
        self.bluePlaceholder.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bluePlaceholder.sizePolicy().hasHeightForWidth())
        self.bluePlaceholder.setSizePolicy(sizePolicy)
        self.bluePlaceholder.setMinimumSize(QtCore.QSize(128, 128))
        self.bluePlaceholder.setMaximumSize(QtCore.QSize(128, 128))
        self.bluePlaceholder.setObjectName(_fromUtf8("bluePlaceholder"))
        self.bluePreview.addWidget(self.bluePlaceholder)
        self.blueContainer.addLayout(self.bluePreview)
        self.blueWavelength_2 = QtGui.QHBoxLayout()
        self.blueWavelength_2.setObjectName(_fromUtf8("blueWavelength_2"))
        self.blueWavelengthLabel_2 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueWavelengthLabel_2.sizePolicy().hasHeightForWidth())
        self.blueWavelengthLabel_2.setSizePolicy(sizePolicy)
        self.blueWavelengthLabel_2.setMinimumSize(QtCore.QSize(90, 0))
        self.blueWavelengthLabel_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.blueWavelengthLabel_2.setText(QtGui.QApplication.translate("RGBComposite", "Wavelength: ", None, QtGui.QApplication.UnicodeUTF8))
        self.blueWavelengthLabel_2.setObjectName(_fromUtf8("blueWavelengthLabel_2"))
        self.blueWavelength_2.addWidget(self.blueWavelengthLabel_2)
        self.blueWavelengthSelect = QtGui.QComboBox(self.verticalLayoutWidget)
        self.blueWavelengthSelect.setMinimumSize(QtCore.QSize(130, 0))
        self.blueWavelengthSelect.setObjectName(_fromUtf8("blueWavelengthSelect"))
        self.blueWavelength_2.addWidget(self.blueWavelengthSelect)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.blueWavelength_2.addItem(spacerItem3)
        self.blueContainer.addLayout(self.blueWavelength_2)
        self.blueWeight = QtGui.QHBoxLayout()
        self.blueWeight.setObjectName(_fromUtf8("blueWeight"))
        self.blueWeightLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.blueWeightLabel.setText(QtGui.QApplication.translate("RGBComposite", "Weight: ", None, QtGui.QApplication.UnicodeUTF8))
        self.blueWeightLabel.setObjectName(_fromUtf8("blueWeightLabel"))
        self.blueWeight.addWidget(self.blueWeightLabel)
        self.blueWeightSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.blueWeightSlider.setMaximum(100)
        self.blueWeightSlider.setProperty("value", 100)
        self.blueWeightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueWeightSlider.setObjectName(_fromUtf8("blueWeightSlider"))
        self.blueWeight.addWidget(self.blueWeightSlider)
        self.blueContainer.addLayout(self.blueWeight)
        self.wavelengthForm.addLayout(self.blueContainer)
        self.outerContainer.addLayout(self.wavelengthForm)
        RGBComposite.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(RGBComposite)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RGBComposite.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(RGBComposite)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("RGBComposite", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        RGBComposite.setMenuBar(self.menubar)
        self.actionSave = QtGui.QAction(RGBComposite)
        self.actionSave.setText(QtGui.QApplication.translate("RGBComposite", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("RGBComposite", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(RGBComposite)
        QtCore.QMetaObject.connectSlotsByName(RGBComposite)

    def retranslateUi(self, RGBComposite):
        pass

