name: 'Notify Matrix'
description: 'Send a notification to the SunPy Developers Matrix room.'
branding:
  icon: message-square
  color: yellow
inputs:
  status:
    description: Status to report (either 'Succeeded' or 'Failed')
    required: true
  token:
    description: Access token for Matrix bot account
    required: true
  roomid:
    description: Matrix room ID to send message to (default is SunPy Development room)
    required: false
    default: '%21JYqfIVJjWANcHnfktY:cadair.com'
  homeserver:
    description: Matrix homeserver
    required: false
    default: 'https://matrix.cadair.com'

runs:
  using: "composite"
  steps:

    - run: |
        sudo apt install -y httpie xonsh
        http --version
      shell: bash

    - uses: actions/checkout@v3

    - run: xonsh ./tools/send_matrix_message.xsh
      shell: bash
      env:
        STATUS: ${{ inputs.status }}
        ROOMID: ${{ inputs.roomid }}
        HOMESERVER: ${{ inputs.homeserver }}
        ACCESS_TOKEN: ${{ inputs.token }}
        BRANCH: ${{ github.ref_name }}
        RUNID: ${{ github.run_id }}
