name: Cancel duplicate workflows

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - requested

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        workflow_id: ${{ github.event.workflow.id }}
