name: Scheduled builds

on:
  # Allow manual runs through the web UI
  workflow_dispatch:
  schedule:
    #        ┌───────── minute (0 - 59)
    #        │ ┌───────── hour (0 - 23)
    #        │ │ ┌───────── day of the month (1 - 31)
    #        │ │ │ ┌───────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────── day of the week (0 - 6 or SUN-SAT)
    - cron: '0 7 * * *'  # Every day at 07:00 UTC

jobs:
  dispatch_workflows:
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run ci.yml --repo sunpy/sunpy --ref main
      - run: gh workflow run ci.yml --repo sunpy/sunpy --ref 4.0
    env:
      GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
